"""
cluster.py
----------
Production clustering script for customer support tickets.
Reads optimal parameters from config.json (generated by tune.py),
runs K-Means and DBSCAN pipelines, evaluates results and saves
models, labels and metrics to disk.

Usage:
    python src/cluster.py

Note:
    Run src/embed.py first to generate embeddings.
    Run src/tune.py first to generate config.json.
"""

import os
import json
import joblib
import numpy as np
import pandas as pd
from sklearn.cluster import KMeans, DBSCAN
from sklearn.preprocessing import normalize
from sklearn.metrics import (
    silhouette_score,
    davies_bouldin_score,
    adjusted_rand_score,
    normalized_mutual_info_score
)
from sklearn.feature_extraction.text import TfidfVectorizer
import umap
import warnings

warnings.filterwarnings("ignore")

# ----- Config -------------------------------------------------------
DATA_DIR    = os.path.join(os.path.dirname(__file__), "..", "data")
MODELS_DIR  = os.path.join(os.path.dirname(__file__), "..", "models")
CONFIG_PATH = os.path.join(os.path.dirname(__file__), "..", "config.json")
EMBEDDINGS_PATH = os.path.join(DATA_DIR, "embeddings.npy")
CSV_PATH        = os.path.join(DATA_DIR, "tickets.csv")


# ----- Load Config --------------------------------------------------
def load_config() -> dict:
    """Load tuned parameters from config.json."""
    with open(CONFIG_PATH, "r") as f:
        config = json.load(f)
    print("Loaded config.json")
    print(f"  K-Means : k={config['kmeans']['k']}, "
          f"UMAP({config['kmeans']['umap_n_neighbors']}, "
          f"{config['kmeans']['umap_n_components']})")
    print(f"  DBSCAN  : eps={config['dbscan']['eps']}, "
          f"UMAP({config['dbscan']['umap_n_neighbors']}, "
          f"{config['dbscan']['umap_n_components']})")
    return config


# ----- Load Data ----------------------------------------------------
def load_data() -> tuple[np.ndarray, pd.DataFrame]:
    """Load embeddings and ticket dataframe from disk."""
    print("\nLoading data...")
    embeddings = np.load(EMBEDDINGS_PATH)
    df = pd.read_csv(CSV_PATH)
    print(f"Loaded {len(df)} tickets, embeddings shape: {embeddings.shape}")
    return embeddings, df


# ----- Normalise ----------------------------------------------------
def normalise(embeddings: np.ndarray) -> np.ndarray:
    """L2 normalise embeddings."""
    return normalize(embeddings)


# ----- UMAP ---------------------------------------------------------
def fit_umap(X: np.ndarray, n_neighbors: int,
             n_components: int) -> tuple[np.ndarray, umap.UMAP]:
    """Fit UMAP and return reduced embeddings and fitted reducer."""
    print(f"  Fitting UMAP (n_neighbors={n_neighbors}, "
          f"n_components={n_components})...")
    reducer = umap.UMAP(
        n_components=n_components,
        n_neighbors=n_neighbors,
        min_dist=0.0,
        metric="cosine",
        random_state=42
    )
    X_reduced = reducer.fit_transform(X)
    return X_reduced, reducer


# ----- Cluster Labels -----------------------------------------------
def label_clusters(df: pd.DataFrame,
                   cluster_col: str, top_n: int = 4) -> dict:
    """
    Generate automatic cluster labels using TF-IDF top keywords.
    Returns dict mapping cluster_id to keyword string.
    """
    labels = {}
    for cluster_id in sorted(df[cluster_col].unique()):
        if cluster_id == -1:
            labels[cluster_id] = "noise"
            continue
        texts = df[df[cluster_col] == cluster_id]["text"].tolist()
        if len(texts) < 2:
            labels[cluster_id] = "too small"
            continue
        tfidf = TfidfVectorizer(stop_words="english", max_features=500)
        tfidf.fit_transform(texts)
        scores = zip(tfidf.get_feature_names_out(), tfidf.idf_)
        top = sorted(scores, key=lambda x: x[1])[:top_n]
        labels[cluster_id] = ", ".join([w for w, _ in top])
    return labels


# ----- Evaluate -----------------------------------------------------
def evaluate(X: np.ndarray, labels: np.ndarray,
             df: pd.DataFrame) -> dict:
    """
    Evaluate clustering quality using unsupervised and supervised metrics.
    Excludes noise points (label=-1) from evaluation.
    """
    mask = labels != -1
    labels_clean = labels[mask]
    X_clean = X[mask]
    df_clean = df[mask]

    n_clusters = len(set(labels_clean))
    n_noise = (labels == -1).sum()

    if n_clusters < 2:
        return {"error": "fewer than 2 clusters — cannot evaluate"}

    sil = silhouette_score(X_clean, labels_clean,
                           sample_size=3000, random_state=42)
    db  = davies_bouldin_score(X_clean, labels_clean)
    ari = adjusted_rand_score(df_clean["intent"], labels_clean)
    nmi = normalized_mutual_info_score(df_clean["intent"], labels_clean)

    return {
        "n_clusters"     : int(n_clusters),
        "n_noise"        : int(n_noise),
        "noise_pct"      : round(float(n_noise / len(labels) * 100), 2),
        "silhouette"     : round(float(sil), 4),
        "davies_bouldin" : round(float(db), 4),
        "ari"            : round(float(ari), 4),
        "nmi"            : round(float(nmi), 4)
    }


# ----- K-Means Pipeline ---------------------------------------------
def run_kmeans(X: np.ndarray, df: pd.DataFrame,
               config: dict) -> tuple[np.ndarray, dict]:
    """Run K-Means clustering pipeline using config parameters."""
    print("\n" + "="*50)
    print("K-Means Pipeline")
    print("="*50)

    km_cfg = config["kmeans"]

    X_umap, reducer = fit_umap(
        X,
        km_cfg["umap_n_neighbors"],
        km_cfg["umap_n_components"]
    )

    print(f"  Fitting K-Means (k={km_cfg['k']})...")
    km = KMeans(
        n_clusters=km_cfg["k"],
        random_state=42,
        n_init=km_cfg["n_init"]
    )
    labels = km.fit_predict(X_umap)

    metrics = evaluate(X_umap, labels, df)

    print(f"\n  Results:")
    for k, v in metrics.items():
        print(f"    {k:<20}: {v}")

    cluster_labels = label_clusters(df.assign(cluster=labels), "cluster")

    print(f"\n  Cluster labels:")
    print(f"  {'Cluster':<10} {'Size':<8} {'Keywords'}")
    print(f"  {'-'*55}")
    for cid, keywords in cluster_labels.items():
        size = (labels == cid).sum()
        print(f"  {cid:<10} {size:<8} {keywords}")

    joblib.dump(km, os.path.join(MODELS_DIR, "kmeans_model.joblib"))
    joblib.dump(reducer, os.path.join(MODELS_DIR, "kmeans_umap.joblib"))
    np.save(os.path.join(DATA_DIR, "umap_kmeans.npy"), X_umap)
    print(f"\n  Saved model, reducer and UMAP embeddings")

    return labels, metrics


# ----- DBSCAN Pipeline ----------------------------------------------
def run_dbscan(X: np.ndarray, df: pd.DataFrame,
               config: dict) -> tuple[np.ndarray, dict]:
    """Run DBSCAN clustering pipeline using config parameters."""
    print("\n" + "="*50)
    print("DBSCAN Pipeline")
    print("="*50)

    db_cfg = config["dbscan"]

    X_umap, reducer = fit_umap(
        X,
        db_cfg["umap_n_neighbors"],
        db_cfg["umap_n_components"]
    )

    print(f"  Fitting DBSCAN (eps={db_cfg['eps']}, "
          f"min_samples={db_cfg['min_samples']})...")
    db = DBSCAN(eps=db_cfg["eps"], min_samples=db_cfg["min_samples"])
    labels = db.fit_predict(X_umap)

    metrics = evaluate(X_umap, labels, df)

    print(f"\n  Results:")
    for k, v in metrics.items():
        print(f"    {k:<20}: {v}")

    joblib.dump(db, os.path.join(MODELS_DIR, "dbscan_model.joblib"))
    joblib.dump(reducer, os.path.join(MODELS_DIR, "dbscan_umap.joblib"))
    np.save(os.path.join(DATA_DIR, "umap_dbscan.npy"), X_umap)
    print(f"\n  Saved model, reducer and UMAP embeddings")

    return labels, metrics


# ----- Comparison ---------------------------------------------------
def print_comparison(km_metrics: dict, db_metrics: dict,
                     config: dict) -> None:
    """Print final K-Means vs DBSCAN comparison table."""
    print("\n" + "="*50)
    print("Final Comparison")
    print("="*50)
    print(f"\n{'Metric':<20} {'K-Means':<12} {'DBSCAN'}")
    print("-" * 45)
    metrics = ["silhouette", "davies_bouldin", "ari", "nmi",
               "n_clusters", "n_noise"]
    for m in metrics:
        print(f"{m:<20} {str(km_metrics.get(m,'')):<12} {db_metrics.get(m,'')}")
    print(f"\nNote: each algorithm evaluated on its own optimal UMAP space.")
    print(f"K-Means UMAP : n_neighbors={config['kmeans']['umap_n_neighbors']}, "
          f"n_components={config['kmeans']['umap_n_components']}")
    print(f"DBSCAN UMAP  : n_neighbors={config['dbscan']['umap_n_neighbors']}, "
          f"n_components={config['dbscan']['umap_n_components']}")


# ----- Save Results -------------------------------------------------
def save_results(df: pd.DataFrame, km_labels: np.ndarray,
                 db_labels: np.ndarray, km_metrics: dict,
                 db_metrics: dict) -> None:
    """Save cluster labels to CSV and metrics to JSON."""
    df["cluster_kmeans"] = km_labels
    df["cluster_dbscan"] = db_labels
    df.to_csv(CSV_PATH, index=False)
    print(f"\nSaved labels to {CSV_PATH}")

    metrics = {
        "kmeans": km_metrics,
        "dbscan": db_metrics
    }
    metrics_path = os.path.join(DATA_DIR, "metrics.json")
    with open(metrics_path, "w") as f:
        json.dump(metrics, f, indent=2)
    print(f"Saved metrics to {metrics_path}")


# ----- Main ---------------------------------------------------------
def main() -> None:
    """Run full clustering pipeline for K-Means and DBSCAN."""
    os.makedirs(MODELS_DIR, exist_ok=True)

    config = load_config()
    embeddings, df = load_data()
    X = normalise(embeddings)

    km_labels, km_metrics = run_kmeans(X, df, config)
    db_labels, db_metrics = run_dbscan(X, df, config)

    print_comparison(km_metrics, db_metrics, config)
    save_results(df, km_labels, db_labels, km_metrics, db_metrics)

    print("\nDone. Models saved to models/")
    print("Labels saved to data/tickets.csv")
    print("Metrics saved to data/metrics.json")


if __name__ == "__main__":
    main()
